update 2 to 2.6.2

diff --git a/2/server/Dockerfile b/2/server/Dockerfile
--- a/2/server/Dockerfile
+++ b/2/server/Dockerfile
@@ -6,12 +6,22 @@
 
 FROM chinayin/debian:bullseye-slim
 
-ENV HFISH_VERSION 2.6.1
+ENV HFISH_VERSION 2.6.2
 
 RUN set -eux; \
   install_packages curl net-tools wget telnet iputils-ping vim; \
+  arch="$(dpkg --print-architecture)"; \
+	case "$arch" in \
+		'amd64') \
+			downloadUrl='https://hfish.cn-bj.ufileos.com/hfish-${HFISH_VERSION}-linux-amd64.tar.gz'; \
+			;; \
+		'arm64') \
+			downloadUrl='https://hfish.cn-bj.ufileos.com/hfish-${HFISH_VERSION}-linux-arm64.tar.gz'; \
+			;; \
+		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+	esac; \
   #
-  curl -fskSL -o hfish.tgz "https://hfish.cn-bj.ufileos.com/hfish-${HFISH_VERSION}-linux-amd64.tar.gz"; \
+  curl -fskSL -o hfish.tgz "$downloadUrl"; \
   mkdir -p /opt/hfish /opt/hfish/tmp; \
   tar -zxvf hfish.tgz -C /opt/hfish; \
   rm -f hfish.tgz; \
